//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Empleados = new HashSet<Empleado>();
        }
    
        public int id_area { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Empleado> Empleados { get; set; }
    }
}
