//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aux_total_categoria_mes
    {
        public Aux_total_categoria_mes()
        {
            this.Valores_mes = new HashSet<Valor_mes_categoria>();
        }
    
        public int id_aux_total_categoria_mes { get; set; }
        public int id_categoria_equipo { get; set; }
        public int mes { get; set; }
        public int anio { get; set; }
    
        public virtual ICollection<Valor_mes_categoria> Valores_mes { get; set; }
    }
}
