//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aux_planilla_gasto_administracion
    {
        public int id_detalle_gastos_administrativos { get; set; }
        public int id_equipo { get; set; }
        public decimal porcentaje { get; set; }
        public int id_planilla_gastos_administartivos { get; set; }
    
        public virtual Planilla_gasto_administrativo Planilla { get; set; }
    }
}
