//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aux_planilla_gasto_administracion
    {
        public int id_detalle_gastos_administrativos { get; set; }
        public int id_equipo { get; set; }
        public decimal porcentaje { get; set; }
        public int id_planilla_gastos_administartivos { get; set; }
    
        public virtual Planilla_gasto_administrativo Planilla { get; set; }
    }
}
