//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aux_planilla_calculo
    {
        public int Id { get; set; }
        public int id_equipo { get; set; }
        public bool considera_guardia { get; set; }
        public int mes { get; set; }
        public int anio { get; set; }
    }
}
