//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aux_planilla_gastos_horas_hombre
    {
        public int Id { get; set; }
        public decimal insumos_taller { get; set; }
        public decimal herramientas { get; set; }
        public decimal viaticos { get; set; }
        public decimal viaticos_presupuestados { get; set; }
        public int mes { get; set; }
        public int anio { get; set; }
        public string tipo_empleado { get; set; }
        public decimal indumentaria { get; set; }
        public decimal repuestos { get; set; }
        public decimal gastos_varios { get; set; }
        public decimal otros { get; set; }
        public decimal repuestos_presupuestados { get; set; }
    }
}
