//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aux_planilla_calculo
    {
        public int Id { get; set; }
        public int id_equipo { get; set; }
        public bool considera_guardia { get; set; }
        public int mes { get; set; }
        public int anio { get; set; }
    }
}
