//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_valor_item_mes_categoria
    {
        public int id_detalle_valor_item_mes_categoria { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal monto { get; set; }
        public string descripcion { get; set; }
        public int id_valor_mes_categoria_item { get; set; }
    
        public virtual Valor_mes_categoria Valor_mes_categoria { get; set; }
    }
}
