//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_dia
    {
        public int id_detalle_dia { get; set; }
        public int id_equipo { get; set; }
        public string hora_desde { get; set; }
        public string hora_hasta { get; set; }
        public int id_dia { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Dia Dia { get; set; }
    }
}
