//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_dia
    {
        public int id_detalle_dia { get; set; }
        public int id_equipo { get; set; }
        public string hora_desde { get; set; }
        public string hora_hasta { get; set; }
        public int id_dia { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Dia Dia { get; set; }
    }
}
