//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    
    public enum Estado_turno_dia : int
    {
        Ninguno = 0,
        Presente = 1,
        Vacaciones = 2,
        Ausente = 3,
        Ausente_injust = 4
    }
}
