//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    
    public enum Estado_turno_dia : int
    {
        Ninguno = 0,
        Presente = 1,
        Vacaciones = 2,
        Ausente = 3,
        Ausente_injust = 4
    }
}
