//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso_egreso_mensual_equipo
    {
        public Ingreso_egreso_mensual_equipo()
        {
            this.Valores_meses = new HashSet<Valor_mes>();
        }
    
        public int id_ingreso_egreso_mensual { get; set; }
        public int id_equipo { get; set; }
        public int mes { get; set; }
        public int anio { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual ICollection<Valor_mes> Valores_meses { get; set; }
    }
}
