//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso_egreso_mensual_equipo
    {
        public Ingreso_egreso_mensual_equipo()
        {
            this.Valores_meses = new HashSet<Valor_mes>();
        }
    
        public int id_ingreso_egreso_mensual { get; set; }
        public int id_equipo { get; set; }
        public int mes { get; set; }
        public int anio { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual ICollection<Valor_mes> Valores_meses { get; set; }
    }
}
