//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_ingreso_egreso
    {
        public Item_ingreso_egreso()
        {
            this.Valores_mes = new HashSet<Valor_mes>();
            this.Hijos = new HashSet<Item_ingreso_egreso>();
            this.Valor_mes_categorias = new HashSet<Valor_mes_categoria>();
        }
    
        public int id_item { get; set; }
        public string tipo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_item_padre { get; set; }
        public Nullable<bool> mostrar_en_equipo { get; set; }
        public Nullable<bool> mostrar_en_trabajo { get; set; }
    
        public virtual ICollection<Valor_mes> Valores_mes { get; set; }
        public virtual ICollection<Item_ingreso_egreso> Hijos { get; set; }
        public virtual Item_ingreso_egreso Padre { get; set; }
        public virtual ICollection<Valor_mes_categoria> Valor_mes_categorias { get; set; }
    }
}
