//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_ingreso_egreso
    {
        public Item_ingreso_egreso()
        {
            this.Valores_mes = new HashSet<Valor_mes>();
            this.Hijos = new HashSet<Item_ingreso_egreso>();
        }
    
        public int id_item { get; set; }
        public string tipo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_item_padre { get; set; }
    
        public virtual ICollection<Valor_mes> Valores_mes { get; set; }
        public virtual ICollection<Item_ingreso_egreso> Hijos { get; set; }
        public virtual Item_ingreso_egreso Padre { get; set; }
    }
}
