//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    
    public enum perfil_usuario : int
    {
        Admin = 1,
        Jefe = 2,
        Supervisor = 3,
        Usuario = 4,
        Seleccionar = 0,
        Sistema = 5
    }
}
