//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planilla_combustible
    {
        public int id_planilla_combustible { get; set; }
        public int id_equipo { get; set; }
        public System.DateTime fecha { get; set; }
        public string chofer { get; set; }
        public bool tanque_lleno { get; set; }
        public decimal litros { get; set; }
        public decimal km { get; set; }
        public decimal promedio { get; set; }
        public decimal costo_total_facturado { get; set; }
        public string lugar { get; set; }
        public Nullable<bool> playa { get; set; }
        public string observaciones { get; set; }
    
        public virtual Equipo Equipo { get; set; }
    }
}
