//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planilla_gasto_administrativo
    {
        public Planilla_gasto_administrativo()
        {
            this.Detalle = new HashSet<Aux_planilla_gasto_administracion>();
        }
    
        public int id_planilla_gastos_administartivos { get; set; }
        public int mes { get; set; }
        public int anio { get; set; }
        public decimal monto_telefonia_celular { get; set; }
        public decimal monto_sueldos { get; set; }
        public decimal monto_honorarios_sistema { get; set; }
        public decimal monto_honorarios_contables { get; set; }
        public decimal monto_papeleria { get; set; }
        public decimal monto_otros { get; set; }
    
        public virtual ICollection<Aux_planilla_gasto_administracion> Detalle { get; set; }
    }
}
