//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resumen_mes_empleado
    {
        public Resumen_mes_empleado()
        {
            this.Sueldo = 0m;
        }
    
        public int id_resumen_mes { get; set; }
        public int id_empleado { get; set; }
        public int mes { get; set; }
        public int anio { get; set; }
        public decimal dias_laborables { get; set; }
        public decimal dias_ausente { get; set; }
        public decimal dias_presente { get; set; }
        public decimal dias_por_cargar { get; set; }
        public decimal dias_out { get; set; }
        public decimal dias_presentes_en_dias_no_laborables { get; set; }
        public string total_horas_normales { get; set; }
        public string total_horas_extra_50 { get; set; }
        public string total_horas_extra_100 { get; set; }
        public decimal Sueldo { get; set; }
        public string total_horas_ausente { get; set; }
        public string total_horas_guardia { get; set; }
        public string total_horas_varios_taller { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
