//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_table_filas_items_mes_equipo
    {
        public int id { get; set; }
        public int id_valor_mes { get; set; }
        public string concepto { get; set; }
        public decimal valor { get; set; }
        public string row_class { get; set; }
        public bool visible { get; set; }
    }
}
