//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_table_filas_items_mes_equipo
    {
        public int id { get; set; }
        public int id_valor_mes { get; set; }
        public string concepto { get; set; }
        public decimal valor { get; set; }
        public string row_class { get; set; }
        public bool visible { get; set; }
    }
}
