//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valor_mes_categoria
    {
        public Valor_mes_categoria()
        {
            this.Detalle = new HashSet<Detalle_valor_item_mes_categoria>();
        }
    
        public int id_valor_mes_categoria_item { get; set; }
        public int id_aux_total_categoria_mes { get; set; }
        public int id_item { get; set; }
        public decimal valor { get; set; }
    
        public virtual Aux_total_categoria_mes Aux_total_categoria_mes { get; set; }
        public virtual Item_ingreso_egreso Item_ingreso_egreso { get; set; }
        public virtual ICollection<Detalle_valor_item_mes_categoria> Detalle { get; set; }
    }
}
