//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valor_mes
    {
        public Valor_mes()
        {
            this.Detalle = new HashSet<Detalle_valor_item_mes>();
        }
    
        public int id { get; set; }
        public int id_ingreso_egreso_mensual { get; set; }
        public int id_item { get; set; }
        public decimal valor { get; set; }
    
        public virtual Item_ingreso_egreso Item { get; set; }
        public virtual ICollection<Detalle_valor_item_mes> Detalle { get; set; }
    }
}
