//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisEquiposBertoncini.Aplicativo.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valor_mes
    {
        public Valor_mes()
        {
            this.Detalle = new HashSet<Detalle_valor_item_mes>();
        }
    
        public int id { get; set; }
        public int id_ingreso_egreso_mensual { get; set; }
        public int id_item { get; set; }
        public decimal valor { get; set; }
    
        public virtual Item_ingreso_egreso Item { get; set; }
        public virtual ICollection<Detalle_valor_item_mes> Detalle { get; set; }
    }
}
